language: python
python: 3.7

dist: xenial

services:
  - docker

before_install:
  - make mysql-container
  - make postgres-container

install:
  - pip install tox

matrix:
  include:
    - python: 3.8
      env: TOX_ENV="py38-sqlalchemylatest"

    - stage: deploy
      script: skip

script:
  - tox -e $TOX_ENV
